### ISSUE TITLE
dogeon.org much broken

### ISSUE THREAD

**Issue by wfalkwallace** [dogescript/DSON#13]
such sad

**Comment by vpzomtrrfrt** [comment]
Until the real one comes back, I've mirrored it at http://vpzomtrrfrt.github.io/DSON/

**Comment by wfalkwallace** [comment]
Thanks @vpzomtrrfrt!

**Comment by RangerMauve** [comment]
Why not just put this under gh-pages under this very repo? Then one could visit http://dogescript.github.ui/DSON

**Comment by vpzomtrrfrt** [comment]
I'm not part of the organization.

**Comment by RangerMauve** [comment]
Err, I was more aiming at the general discussion than you in particular. :P

**Comment by JDeuce** [comment]
It's also now available along with the dsonlint tool here 
http://dsonlint.github.io/spec/.

**Comment by vpzomtrrfrt** [comment]
Here, have http://dogeon.xyz

**Comment by cerlestes** [comment]
Oh man, I love you guys :D Sorry that I've abandoned the project, but also Zach (@remixz) had lost his interest shortly after the hype stopped. It was a fun project and I love to see it continued. If you want to take over the DSON project, by all means, please contact me.

**Comment by arrdem** [comment]
I'd be pleased to take it over, if only for the "you maintain what?!" value.

**Comment by AnEmortalKid** [comment]
@arrdem sorry we spaced out on this. Do you want to be the fore front for this? I own the dogescript.io. I could see about setting up dson.dogescript.io or maybe try to snag dson.io 

Let us know. The dogescript readme has a section on joining a slack channel if you want to come chat.

**Comment by benatkin** [comment]
@AnEmortalKid let's use https://dogeon.xyz/ - no need to register a new one! I'm impressed that you've kept it live all this time @vpzomtrrfrt. A big ![](https://git.io/doge) high five to ya!

**Comment by benatkin** [comment]
I announced it on twitter: https://twitter.com/dogescript/status/983784956378927104

<img width="672" alt="screen shot 2018-04-10 at 3 17 24 pm" src="https://user-images.githubusercontent.com/4126/38578585-587b69c4-3cd2-11e8-9ab5-62603be03cc4.png">

**Comment by cerlestes** [comment]
I would not have thought that people will still care about this so many years later. I've let the domain expire because the spam and scams due to whois information became insane. Love to all of y'all shibe, you guys rock <3
