### ISSUE TITLE
dsongo-by-muhammad branch is not merged with the master branch

### ISSUE THREAD

**Issue by muhammadmuzzammil1998** [dogescript/DSON#21]
I think there has been some confusion... The master branch is not up to date with the dsongo-by-muhammad branch thats why it doesn't show on the website. Please merge them.

Previous issue: #17 

Thanks! :)

**Comment by AnEmortalKid** [comment]
Merged! I believe it now auto-publishes (I see a dson-go (Parser/Serializer (by muhammadmuzzammil1998)) now on the site!

**Comment by muhammadmuzzammil1998** [comment]
Yes, thank you :)

![image](https://user-images.githubusercontent.com/12321712/46452996-88efdc00-c7bc-11e8-8c67-cbb1f3fc7a80.png)
